---
- name: restart node_exporter
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted

- name: restart service_node_exporter
  service:
    name: node_exporter
    state: restarted
