---
- name: Check OSSEC agent client.keys exists
  stat:
    path: '/var/ossec/etc/client.keys'
  register: check_ossec_keys

- name: Check register manager are accessible from current host
  wait_for:
    host: '{{ ossec_agent_authd.address }}'
    port: '{{ ossec_agent_authd.port }}'
    state: 'started'
    delay: 0
    timeout: 5
  changed_when: false
  failed_when: false
  register: check_ossec_reg

- name: OSsec agent operation
  block:
    - name: Include tasks for specific OS
      include: '{{ ansible_system }}/{{ ansible_os_family }}.yml'
    - name: Configuration the OSQuery
      include: '{{ ansible_system }}/osquery.yml'
    - name: Configuration the OSSEC agent
      include: '{{ ansible_system }}/configureation.yml'
    - name: Reload the OSSEC agent service
      shell: echo ''
      notify: 'Ensure OSSEC agent service is enabled'
      when: ossec_agent_auth_output.rc == 0
    - name: Force the handler to run immediately
      meta: flush_handlers
    - name: Remove OSSec metadata
      include: '{{ ansible_system }}/cleanup.yml'
  when:
    - check_ossec_reg.state is defined
    - check_ossec_reg.state == 'started'
    - not check_ossec_keys.stat.exists or check_ossec_keys.stat.size == 0
