---
# openresty pkgs depend parameter
# openresty
openresty_ver : '1.13.6.1'
openresty_mirror : https://openresty.org/download
openresty_build_dir : /usr/local/src/openresty
openresty_install_dir : /usr/local/openresty
openresty_timeout_seconds : 600

# openresty_checksum: '{{openresty_checksums[openresty_ver]}}'
openresty_name : 'openresty-{{openresty_ver}}'
openresty_tgz : '{{openresty_name}}.tar.gz'
openresty_url : '{{openresty_mirror}}/{{openresty_tgz}}'

# luajit
luajit_ver : '2.1'
luajit_dir : '{{openresty_install_dir}}/luajit'
luajit_include_dir : '{{luajit_dir}}/include/luajit-{{luajit_ver}}'

# opm
luarocks_module_deploy : True

luarocks_ver : '2.4.4'
luarocks_mirror : http://luarocks.github.io/luarocks/releases
luarocks_build_dir : /usr/local/src/luarocks
luarocks_timeout_seconds : 600

# luarocks_checksum: '{{luarocks_checksums[luarocks_ver]}}'
luarocks_name : 'luarocks-{{luarocks_ver}}'
luarocks_tgz : '{{luarocks_name}}.tar.gz'
luarocks_tgz_url : '{{luarocks_mirror}}/{{luarocks_tgz}}'

luarocks_install :
  - luasec
  - luajson
  - lua-resty-http

# module
# drizzle
drizzle_module_deploy : True

drizzle_ver : '2011.07.21'
drizzle_url : https://openresty.org/download/drizzle7-2011.07.21.tar.gz
drizzle_build_dir : /usr/local/src/drizzle
drizzle_name : 'drizzle7-{{drizzle_ver}}'
drizzle_tgz : '{{drizzle_name}}.tar.gz'


# pkgs
openresty_pkgs :
  - pcre-devel
  - openssl-devel
  - gcc
  - gcc-c++
  - curl
  - postgresql-devel
  - wget
  - perl
  - gd
  - gd-devel
  - readline-devel
  - openldap-devel
  - zlib-devel
  - make
  - unzip
  - zlib-devel
  - gettext
  - libxslt-devel
  - perl-ExtUtils-Embed
  - GeoIP-devel

# RESTY_CONFIG_OPTIONS
openresty_j: 2
openresty_config_options : |
    --with-file-aio
    --with-http_addition_module
    --with-http_auth_request_module
    --with-http_dav_module
    --with-http_flv_module
    --with-http_geoip_module=dynamic
    --with-http_gunzip_module
    --with-http_gzip_static_module
    --with-http_image_filter_module=dynamic
    --with-http_mp4_module
    --with-http_random_index_module
    --with-http_realip_module
    --with-http_secure_link_module
    --with-http_slice_module
    --with-http_ssl_module
    --with-http_stub_status_module
    --with-http_sub_module
    --with-http_v2_module
    --with-http_xslt_module=dynamic
    --with-ipv6
    --with-mail
    --with-mail_ssl_module
    --with-md5-asm
    --with-pcre-jit
    --with-sha1-asm
    --with-stream
    --with-stream_ssl_module
    --with-threads
    --with-http_drizzle_module
    --with-http_iconv_module

openresty_cleanup : False
#openresty_cleanup : True
