- name: Create Docker dir
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - /etc/docker
    - /etc/systemd/system/docker.service.d
    - /etc/sysctl.d

- name: Configure Docker daemon json
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0644"
  when: docker__default_daemon_json | d() or docker__daemon_json | d()

- name: Configure Docker sysctl.conf
  template:
    src: "100-docker.conf.j2"
    dest: "/etc/sysctl.d/100-docker.conf"

- name: Configuration to modprobe br_netfilter
  shell: modprobe br_netfilter

- name: Configuration to take effect (sysctl)
  shell: sysctl -p /etc/sysctl.d/100-docker.conf

- name: Disable Swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes
- name: Disable Swap
  shell: |
    swapoff -a

