---
# vars item
# root_group: root
# nginx_conf_path: /etc/nginx/conf.d
# nginx_conf_file_path: /etc/nginx/nginx.conf
# nginx_mime_file_path: /etc/nginx/mime.types
# nginx_pidfile: /var/run/nginx.pid
# nginx_vhost_path: /etc/nginx/conf.d
# nginx_default_vhost_path: /etc/nginx/conf.d/default.conf
# __nginx_user: "nginx"

# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx package to install.
#nginx_package_name: "nginx-1.16.1"
nginx_package_name: "nginx-1.18.0"

nginx_service_state: started
nginx_service_enabled: true

nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "vhost.j2"

nginx_worker_processes: >- 
  auto
#nginx_worker_processes: >-
#  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"

# worker_rlimit_nofile = (ulimit -n)
nginx_rlimit_nofile: 65530

# use [ kqueue | rtsig | epoll | /dev/poll | select | poll ];
nginx_event_module: epoll

# nginx_worker_connections = 单个进程最大连接数（最大连接数=连接数+进程数）
nginx_worker_connections: "1024"
nginx_multi_accept: "off"
# default 1k 
nginx_client_header_buffer_size: "4k" 

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_server_tokens: "off"

nginx_client_max_body_size: "64m"

#nginx_server_names_hash_bucket_size: "64"
nginx_server_names_hash_bucket_size: "128"

nginx_proxy_cache_path: ""

#nginx_fastcgi_options: ""
nginx_fastcgi_options: |-
  fastcgi_connect_timeout 300;
  fastcgi_send_timeout 300;
  fastcgi_read_timeout 300;
  fastcgi_buffer_size 64k;
  fastcgi_buffers 4 64k;
  fastcgi_busy_buffers_size 128k;
  fastcgi_temp_file_write_size 128k;

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

#nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
nginx_extra_http_options: |-
      proxy_redirect off;
      proxy_ignore_client_abort on;
      proxy_buffering    off;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Scheme $scheme;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   Host $http_host;
      proxy_set_header   REMOTE-HOST $remote_addr;
      proxy_set_header   CLIENT-IP $remote_addr;
      proxy_connect_timeout 30;
      proxy_send_timeout 30;
      proxy_read_timeout 60;
      proxy_buffer_size 256k;
      proxy_buffers 4 256k;
      proxy_busy_buffers_size 256k;
      proxy_temp_file_write_size 256k;
      proxy_next_upstream error timeout;
      proxy_max_temp_file_size 128m;



#nginx_gzip_options: ""
nginx_gzip_options: |-
  gzip on;
  gzip_min_length  1k;
  gzip_buffers     4 16k;
  gzip_http_version 1.0;
  gzip_comp_level 2;
  gzip_types text/plain text/javascript application/x-javascript application/javascript text/css application/xml;
  gzip_vary on;

#nginx_add_header: ""
nginx_add_header: "test"

nginx_remove_default_vhost: false

nginx_vhosts: []
#nginx_vhosts: 
# Example vhost below, showing all available options:
# - listen: "80" # default: "80"
#   server_name: "example.com" # default: N/A
#   root: "/var/www/example.com" # default: N/A
#   index: "index.html index.htm" # default: "index.html index.htm"
#   filename: "example.com.conf" # Can be used to set the vhost filename.

#   # Properties that are only added if defined:
#   server_name_redirect: "www.example.com" # default: N/A
#   error_page: ""
#   access_log: ""
#   error_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).
#   template: "" # Can be used to override the `nginx_vhost_template` per host.
#   state: "absent" # To remove the vhost configuration.

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
