---
# 主任务参数 
# 1.是否执行主机初始配置
os_config: true   

# 2.是否挂载数据盘
os_datadisc: false

# 3.是否执行主机加固配置。
os_harden: true   

# 4.是否执行主机基本软件安装和更新。
os_software: true                        

# 5.是否部署入侵检测客户端。
os_ossec: false    

# Linux 初始参数                          ---> 配置文件 config.yml 
os_linux_tz: 'Asia/Shanghai'              # 主机时区。
os_linux_id_rsa: true                     # 复制当前主机SSH密钥到目标主机。
os_linux_sysctl: false                    # 开启内核参数
os_linux_disable_unused_service: true     # 是否禁用不需要的服务。
os_linux_enables_needed_service: true     # 是否启用需要的服务。
os_linux_disable_sysstat_collect: false   # 是否禁用sysstat监测。
os_linux_resolver_single_request: true    # 启用域名解析单一请求。
os_linux_shell_history: '5000'            # 历史记录存储在内存中的行数。
os_linux_shell_timeout: '9000'            # 系统终端空闲等待时间(秒)。
os_linux_syslog_local_keep: '2'           # 本地日志保留期(周)。
os_linux_ulimit_nofile: '65535'           # 会话打开的文件/文件描述符的最大数目。
os_linux_ulimit_nproc: '65535'            # 会话打开的系统进程的最大数目。
os_disable_ipv6: false                    # 是否关闭IPv6。
os_linux_motd: true                       # 开启登录信息提示。
os_linux_motd_service: '("fail2ban" "ufw" "lxd" "netdata" "zed" "smartd" "postfix" "sshd")'
#os_linux_MTA_relayhost: '1.1.1.1'        # 邮件中继服务器地址。
#os_proxy_server: 'http://1.1.1.1:3142'   # 主机代理服务器。
#os_dns_search: 'dc01.local'              # 域名系统默认搜索域。
os_dns_server:                            # 域名系统服务器。
  - '223.5.5.5'
  - '114.114.114.114'
  - '8.8.8.8'

os_time_server:                           # 时间服务器。
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'

# syslog远程日志参数                          ---> 配置文件 rsyslog.yml
syslog: false                                 # 是否启用远程日志。
syslog_port: '12201'                          # 远程日志服务器端口。
syslog_protocol: 'udp'                        # 远程日志服务器协议。
syslog_server:                                # 远程日志服务器地址列表。
  - '127.0.0.1'
    
# Linux 数据盘参数                            ---> 配置文件 datadisc.yml 
os_linux_disc_device: 'sdb'                   # 数据盘块设备。
os_linux_fsopts: 'defaults,noatime,nobarrier' # 数据盘挂载参数。
os_linux_fstype: 'xfs'                        # 数据盘文件系统。
os_linux_lv: 'lv_data'                        # 逻辑卷名称。
os_linux_lv_size: '100%FREE'                  # 逻辑卷容量。
os_linux_mount_point: '/data'                 # 逻辑卷挂载点。
os_linux_vg: 'VG01'                           # 逻辑卷卷组名称。

# 主机加固配置参数                            ---> 配置文件 harden.yml 
os_linux_sshport: 22                          # ssh_port 
os_linux_disable_RootLogin: false             # 是否禁用root登录。
os_linux_disable_selinux: true                # 是否禁用selinux。
#os_update_password: 'changeme'               # 修改新部署Linux主机管理账户密码。

# 审计参数                                    ---> 配置文件 audit.yml 
os_audit: false                               # 是否启用主机审计。
os_audit_type: 'auditbeat'                    # 审计进程服务类型，auditbeat 或 auditd。
os_auditbeat_version: '7.7.1'                 # Beats 版本。
os_auditbeat_output:                          # Beats 数据收集器参数。
  type: 'elasticsearch'
  elasti_host: '{{ syslog_server }}'
  elasti_port: '9200'
  kibana_host:
    - 'monitor-production-kibana.service.dc01.local'
  kibana_port: '5601'
  https: true
  auth: true
  user: 'elastic'
  pass: 'changeme'
os_auditbeat_port_arg:                        # Beats 通信端口。
  http: '5067'
  exporter: '9480'

# Linux 审计规则
os_linux_audit_rules:
  - '-w /sbin/insmod -p x -k modules'
  - '-w /sbin/rmmod -p x -k modules'
  - '-w /sbin/modprobe -p x -k modules'
  - '-a always,exit -F arch=b32 -S init_module -S delete_module -k modules'
  - '-a always,exit -F arch=b64 -S init_module -S delete_module -k modules'
  - '-a always,exit -F arch=b64 -S mount -k mounts'
  - '-a always,exit -F arch=b32 -S mount -k mounts'
  - '-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale'
  - '-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale'
  - '-w /etc/issue -p wa -k system-locale'
  - '-w /etc/issue.net -p wa -k system-locale'
  - '-w /etc/hosts -p wa -k system-locale'
  - '-w /etc/sysconfig/network -p wa -k system-locale'
  - '-w /var/log/sudo.log -p wa -k actions'
  - '-w /etc/sudoers -p wa -k scope'
  - '-w /etc/sudoers.d -p wa -k scope'
  - '-w /etc/group -p wa -k identity'
  - '-w /etc/passwd -p wa -k identity'
  - '-w /etc/gshadow -p wa -k identity'
  - '-w /etc/shadow -p wa -k identity'
  - '-w /etc/security/opasswd -p wa -k identity'
  - '-a exclude,always -F msgtype=CWD'
  - '-a exclude,always -F msgtype=EOE'
  - '-a never,exit -F dir=/tmp -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a never,exit -F dir=/tmp -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a never,exit -F dir=/var -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a never,exit -F dir=/var -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a never,exit -F dir=/run -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a never,exit -F dir=/run -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a never,exit -F dir=/dev/shm -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a never,exit -F dir=/dev/shm -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -k delete'
  - '-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -k delete'

# 入侵检测系统参数 #
ossec_version: '3.10.2-1'                   # WAZUH代理版本。
ossec_managers:                             # WAZUH管理器参数。
  address:
    - '1.1.1.1'
  port: '1517'
  protocol: 'tcp'
  api_port: '55000'
  api_proto: 'https'
  api_user: null
ossec_agent_authd:                          # WAZUH代理注册参数。
  address: '{{ ossec_managers.address[0] }}'
  authd_pass: 'Bf6vJRT4WaEAHq'
  port: '1515'
  ssl_auto_negotiate: 'no'
ossec_agent_config:                         # WAZUH代理参数。
  auto_restart: 'yes'
  notify_time: '10'
  time_reconnect: '60'
  crypto_method: 'aes'
  active_response:
    ar_disabled: 'no'
    ca_store: '/var/ossec/etc/wpk_root.pem'
    ca_store_win: 'wpk_root.pem'
    ca_verification: 'yes'
  log_format: 'plain'

# consul(公共领事)配置参数 #
environments: 'Development'                # 定义系统环境。
datacenter: 'dc01'                         # 定义数据中心。
domain: 'local'                            # 定义域信息。
#hardware_sn: 'XXXXXXX'                    # 设备序列编号。
#hardware_pn: 'XXXXXXXXXXX'                # 设备服务编号。
#hardware_cu: 'A-1'                        # 设备机架编号。
#tags:                                     # 对象自定义标签
#  subscription: 'default'
#  owner: 'nobody'
#  department: 'Infrastructure'
#  organization: 'The Company'
#  region: 'China'
consul_public_register: false              # 是否向公共领事注册普罗米修斯终端。
consul_public_exporter_token: '00000000-0000-0000-0000-000000000000' # 公共领事客户端访问控制令牌。
consul_public_http_port: '8500'            # 公共领事公共客户端端口。
consul_public_http_prot: 'https'           # 公共领事公共客户端协议。
consul_public_clients:                     # 公共领事公共客户端列表。
  - '127.0.0.1'
