---
- hosts: ops
  roles:
  - ansible-webhook_dingtalk
  vars:
    webhook_dingtalk_config_dir: "/etc/dingtalk"
    webhook_dingtalk_binary_local_dir: "/usr/local/src/prometheus-webhook-dingtalk-1.4.0.linux-amd64"
    webhook_dingtalk_version: 1.4.0
    webhook_dingtalk_web_listen_address: "192.168.100.102:8060"
    webhook_dingtalk_flags:
      - web.enable-ui
      - web.enable-lifecycle
      - config.file=/etc/dingtalk/config.yml
