---
- hosts: all
  become: yes
  remote_user: root
  roles:
  - ansible-zabbix-agent
  vars:
    zabbix_agent_version: 4.0
    zabbix_agent_server: 103.91.156.220
    zabbix_agent_serveractive: 103.91.156.220
    zabbix_agent_listenport: 30050 #set
    zabbix_agent_server_url: "http://zabbix.eminxing.com"
    zabbix_host_groups:
      - Linux servers
    zabbix_link_templates:
      - Template Linux System Base
      - Template_Linux_Process_Top
    zabbix_repo_yum:
      - name: zabbix
        description: Zabbix Official Repository - $basearch
        #baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ zabbix_agent_distribution_major_version }}/$basearch/
        baseurl: https://mirrors.aliyun.com/zabbix/zabbix/{{ zabbix_version }}/rhel/{{ zabbix_agent_distribution_major_version }}/$basearch/
        priority: 1
        gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
        state: present
      - name: zabbix-non-supported
        description: Zabbix Official Repository non-supported - $basearch
        #baseurl: http://repo.zabbix.com/non-supported/rhel/{{ zabbix_agent_distribution_major_version }}/$basearch/
        baseurl: https://mirrors.aliyun.com/zabbix/non-supported/rhel/{{ zabbix_agent_distribution_major_version }}/$basearch/
        priority: 1
        gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
        state: present

    # Zabbix API stuff
    zabbix_agent_server_url: "http://192.168.100.11/zabbix" #set
    zabbix_url: "{{ zabbix_agent_server_url }}"
    
    # 基于api访问zabbix网址
    #zabbix_api_user: Admin  #set
    #zabbix_api_pass: zabbix  #set
    zabbix_api_user: zt15260
    zabbix_api_pass: zt15260@zhongshixun

    # 基本身份验证访问zabbix网址的http用户
    # zabbix_api_http_user: admin
    # zabbix_api_http_password: admin
    
    # 启用Zabbix API创建/删除主机或者主机组时，api_create_host* 为True
    zabbix_api_crete_hostgroup: False
    zabbix_api_create_hosts: False

    # zabbix_api_create_hostgroup = True ,present 创建主机组，absent 删除主机组
    zabbix_create_hostgroup: present  # or absent
    zabbix_create_host: present       # or absent
    
    # zabbix_api_create_hosts = True ,更新已有主机
    zabbix_update_host: yes
    zabbix_host_status: enabled       # or disabled
    zabbix_proxy: null
    
    # 配置Zabbix库存模式,automatic 为自动生成库存数据。
    zabbix_inventory_mode: disabled
    
    # 1:ip, 0:fqdn
    zabbix_useuip: 1
    
    zabbix_agent_userparameters: #set
      - name: disk
        scripts_dir: disk
      - name: memory
        scripts_dir: memory
      - name: network_connect
      - name: process
        scripts_dir: process
      - name: redis
        scripts_dir: redis
      - name: memcached
        scripts_dir: memcached
      - name: mysql
    

