---
- hosts: ops
  pre_tasks:
    - name: Yum install yum-utils
      yum:
        name: yum-utils
        state: present
    - name: Install the MySQL repo
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"
    - name: disable mysql80-community
      shell: yum-config-manager --disable mysql80-community
    - name: enable mysql57-community
      shell: yum-config-manager --enable mysql57-community

    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-community-server','MySQL-python','perl-DBD-MySQL']
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
  roles:
    - ansible-mysql
