---
- name: Check register client are accessible from current host
  uri:
    url: '{{ consul_public_http_prot }}://{{ item }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'GET'
    timeout: '5'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ item }}'
  loop: '{{ consul_public_clients }}'
  changed_when: false
  failed_when: false
  register: check_consul_reg

- name: Register exporter service with an http health check
  uri:
    url: '{{ consul_public_http_prot }}://{{ item.client }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["prometheus","exporter"],"ID":"{{ inventory_hostname | upper }}_{{ os_linux_exporter_type_item.name }}_exporter","name":"{{ os_linux_exporter_type_item.name }}_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ os_linux_exporter_type_item.port }},"meta":{"metrics_path":"/{% if os_linux_exporter_type_item.name == "netdata" %}api/v1/allmetrics?format=prometheus&help=yes{% else %}metrics{% endif %}","instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[-1] | upper }}","datacenter": "{{ datacenter | lower }}","domain":"{{ domain | lower }}","environment":"{{ environments | upper }}"{% if hardware_cu is defined %},"CabinetUnits":"{{ hardware_cu }}"{% endif %}{% if hardware_sn is defined %},"ServiceTag":"{{ hardware_sn }}"{% endif %}{% if hardware_pn is defined %},"ExpressServiceCode":"{{ hardware_pn }}"{% endif %}{% if tags is defined %},{{ tags | to_json | regex_replace("{") | regex_replace("}") }}{% endif %}},"checks":[{"tcp":"{{ ansible_default_ipv4.address }}:{{ os_linux_exporter_type_item.port }}","interval":"60s","timeout":"10s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ item.client }}'
  loop: "{{ check_consul_reg.results | json_query('[*].{client:item,status:status}') }}"
  when:
    - item.status == 405
  register: register_status
  until: register_status.status == 200
  retries: 2
  delay: 2
  no_log: true
  changed_when: false
  failed_when: false
