smokeping:
  container_name: smokeping
  hostname: "smokeping_google"
  image: uxun/smokeping:v0.1
  ports:
    - 8088:80
  volumes:
    - /data/smokeping/ssmtp:/etc/ssmtp
    - /data/smokeping/etc:/opt/smokeping/etc
    - /data/smokeping/data:/opt/smokeping/data
  restart: "always"
  mem_limit: "200M"
  log_opt:
    max-size: '10m'
    max-file: '3'
